services:
  mongodb:
    image: mongo:6.0
    container_name: allstars-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wiki-network
    restart: always

  wiki:
    build: .
    container_name: allstars-wiki-minimal
    user: "node"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./articles
        target: /app/articles
        bind:
          create_host_path: true
      - type: volume
        source: wiki_uploads
        target: /app/public/uploads
    environment:
      - NODE_ENV=production
    command: >
      sh -c "chown -R node:node /app/articles &&
             chmod -R 755 /app/articles &&
             node server.js"
    depends_on:
      - mongodb
    networks:
      - wiki-network
    restart: always

networks:
  wiki-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  wiki_uploads:
    driver: local
