services:
  mongodb:
    image: mongo:6.0
    container_name: allstars-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wiki-network
    restart: always

  wiki:
    build: .
    image: allstars-wiki-minimal:latest
    container_name: allstars-wiki-minimal
    user: "node"
    ports:
      - "3000:3000"
    volumes:
      - ./public/articles:/app/public/articles
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - wiki-network
    restart: always

networks:
  wiki-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
