services:
  mongodb:
    image: mongo:6.0
    container_name: allstars-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wiki-network
    restart: always

  wiki:
    build: .
    container_name: allstars-wiki-minimal
    user: "node"
    ports:
      - "3000:3000"
    volumes:
      - /root/allstars-minimal/public/data/articles:/app/articles
      - wiki_uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - wiki-network
    restart: always

networks:
  wiki-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  wiki_uploads:
    driver: local
